### ISSUE TITLE
Add disk encryption

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/talos#2234]
Disk encryption will involve a number of different pieces.  We have a chicken-and-egg problem with encryption in that the main encryption routines will need to be configured, but we also need the configuration itself (the state partition) encrypted.  So, we likely will need one story for opportunistic encryption of the state partition and another for described encryption of other partititions (ephemeral, primarily).

The state partition contains explicitly local data, so it seems reasonable to consider local-only encryption keys here.  We could either use a deterministic symmetric key, based on the machine's UUID (not as secure, but should be available most anywhere), or opportunistically using the TPM for local key storage.  Eventually, it would be best to separate private data from config data, so this _may_ be viewed as merely a short-term solution.

- Prerequisites:
  - [ ] encryption of state partition (which contains config) #2785
    - could use gocryptfs for simplicity/flexibility, or simple age on the config file (but this is not as flexible over time, as the state partition usage grows to other files)
    - dm-crypt is also fine
    - local keystore (NVRAM/TPM) should probably be sufficient for this, as a first round, maybe even by default, if available
  - [x] Configuration fields:
    - encryption mode (none, ephemeral, local, keyserver)
    - mode-oriented configuration options
    - perhaps `machine.encryption.mode`?
  - [x] LUKS/dm-crypt mount handler #2786
    - determine if partition is encrypted (this is handled by the LUKS mechanism)
    - determine what type of key store is used
    - retrieve key (or create new key and reformat), depending on key store config
- [ ] Three initial key management packages:
  - [ ] Ephemeral (throw-away) keys for single-boot encryption #2642 
  - [ ] Key server (such as clevis/tang) (addresses assurance of recovery while supplying encryption-at-rest)
  - [ ] Local persistent keystore (NVRAM/TPM) (addresses cross-boot stability without transmission of keys over network)
- [x] adv handling - add support for long fields (?), field for "encrypted" flag
- [x] block device library - support disk mapper
- [x] handle opening/closing encrypted devices
- [x] config fields for encrypted system partition & config partition (same for additional disks?)
- [x] encrypt disks during install (?) / boot time (?)
- [ ] tests?

Possible tools:
 - [Luks.go](https://github.com/anatol/luks.go)
 - [gocryptfs](https://github.com/rfjakob/gocryptfs)
 - [age](https://github.com/FiloSottile/age)
 - [clevis/tang](https://github.com/latchset/clevis)
 - [sharedsecret](https://github.com/posener/sharedsecret) Shamir's Secret Sharing Algorithm

**Comment by salkin** [comment]
Would option to use use the TPM to store the encryption key for the node on bare metal be feasible to you? This would help that only that particular node can boot the hard drive.

**Comment by andrewrynhard** [comment]
> Would option to use use the TPM to store the encryption key for the node on bare metal be feasible to you? This would help that only that particular node can boot the hard drive.

This sounds very interesting. Something we have discussed before. I think in general we could use the TPM for a number of things.

**Comment by smira** [comment]
Some links: https://godoc.org/github.com/google/go-tpm/tpm2

https://github.com/zajdee/tpm-luks

**Comment by smira** [comment]
Old issue, now many disk encryption options are supported, including TPM with SecureBoot.
