### ISSUE TITLE
generator for protobuf representation of COSI resources

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#4417]
## Feature Request

Convert native Go struct which represents a resource (e.g. `LinkStatusSpec`) to a `.proto` file under `api/resources/...` and methods `MarshalToProto`, `UnmarshalFromProto`.

**Comment by DmitriyMV** [comment]
🆒

**Comment by DmitriyMV** [comment]
- [ ] Manually implement proto messages for common structures and converters from/to original types
   - [ ] github.com/talos-systems/crypto/x509.PEMEncodedCertificateAndKey
   - [ ] github.com/talos-systems/crypto/x509.PEMEncodedKey
   - [ ] netaddr.IP (maybe it have default represenation?)
   - [ ] netaddr.IPPort
   - [ ] netaddr.IPPrefix
   - [ ] Investigate other common types
   - [ ] Unstructured type which can be constructed from\to JSON
- [ ] Rewrite structure fields with "protobuf" tags - 'protobuf:<field_number>'
   - [ ] Investigate if we can use https://github.com/quasilyte/go-ruleguard  
   - [ ] Investigate if we can use gofix existing source
   - [ ] Given pkg it should update every *Spec struct which is included in Resources. 
- [ ] Implement encoder/decoder "generation" - generate the source code or implement it in runtime
   - [ ] Start with simple struct
   - [ ] Add usage of common structures
   - [ ] Maybe try with reflection based implementation first?
 - [ ] Generate proto files for *Spec structures
 - [ ] Decide between talos resource API and cosi resource API (or maybe something in between)
 - [ ] Remove everywhere (talosctl for example) YAML hacks 

Split it into several self-contained PR's.

See also:
- https://developers.google.com/protocol-buffers/docs/encoding
- https://pkg.go.dev/google.golang.org/protobuf@v1.28.0/encoding/protowire
- Maybe look for Kubernetes marshaller K8s resources?
