### ISSUE TITLE
Interactive Console

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#6752]
Read-only dashboard view running on a virtual TTY for a physical console:

- "status" view (see a mock below)
- "monitor" view (what `talosctl dashboard` is right now)
- "network config edit" view (for `metal` platform only):
  - Hostname
  - Interfaces
  - NTP Servers
  - Name Servers
  - Configuration URL

The interactive console can be disabled via a kernel arg (e.g. `talos.experimental.console.interactive=0`). 

A networking configuration validation will be implemented to ensure network connectivity.

## `metal` platform network config

Metal platform network config is stored in `META` partition (survives partial machine reset). It can be written as well during image creation (at the factory).

Interactive console network config editor modifies that config in `META`.

## interactive console

- VTTY switching
- run interactive console on the second tty (keeping kernel logs on the first one)
- interactive console: scroll dmesg at the bottom, UI at the top, show some status, UI to edit the `edge` platform network config

## Network Validation

A field in which a user can enter a `host:port` that is used to check if the network is configured properly.
Talos runs a check in the background and reports status.

```yaml
metadata:
  id: internal
  type: Health.networ.talos.dev
spec:
  tcp:
    endpoint: ping.siderolabs.io:443
  interval: 30s
```

```yaml
metadata:
  id: internal
  type: HealthStatus.networ.talos.dev
spec:
  ok: true
  error: connection refused
````

## Configuration URL

Only available in `maintenance` mode and `metal` platform. 
Setting that option makes `metal` platform quit maintenance mode and start fetching machine config.

## GRUB option to drop to maintenance mode

In addition to A/B boot option add an option to wipe EPHEMERAL/STATE, and drop to maintenance  mode.

## Workstreams

- [x] #6841 
- [x] #4790  UI development: could be done in `talosctl` standalone, extending `talosctl dashboard` 
- [x] #4791 Linux VTTY, switching screen resolution, etc.; bundling `talosctl dashboard` to run on vtty1
- bare-metal "platform network config" implementation - `META`
- network health checks
- configuration URL
- [x] #6842 GRUB option to drop to maintenance mode

**Comment by sanmai-NL** [comment]
I think this a major shift in the requirements. In the FAQ, you state there's no console in Talos Linux and [Sidero Labs argue this being a key differentiator](https://www.talos.dev/v1.3/learn-more/faqs/#how-is-talos-different-from-other-container-optimized-linux-distros). I also think that the more interactive manipulation you offer, the farther you diverge from the immutability and infra-as-code paradigms,.

I focusing on easier SDK for operators to work with, e.g. integration as [Pulumi provider](https://www.pulumi.com/registry/) a better way forward?

**Comment by sanmai-NL** [comment]
The immutability is kept if this is truly read-only, but this sentence caused confusion:

> Interactive console network config editor modifies that config in META.

**Comment by smira** [comment]
This doesn't change much in fact - as you can enter GRUB and change kernel args, same way you could edit network settings having access to the physical console of the box.  On bare-metal it's often a problem to get the initial network setup to establish API access to the node, so this issue bridges that gap.

We already provide Terraform and Pulumi providers btw, but they operate given that the node has network access already.

**Comment by andrewrynhard** [comment]
A slight addition here:

The user would like to set a kernel arg with a base URL for the Talos config endpoint so that their users only need to enter a code. I imagine this could be fairly simple. A kernel arg like `talos.config.base` (e.g. `talos.config.base=https://endpoint.com/config?code=`. The field we use to present the endpoint could then just be appended to the base URL.

**Comment by frezbo** [comment]
we already have `talos.config` i guess it makes it sense to ask the user for the code if the interactive console is enabled and fetching from url returns it needs auth. Just makes things easier to re-use exsiting args. Or could be just `talos.config=<url>?code=`

**Comment by utkuozdemir** [comment]
Also see: https://github.com/siderolabs/talos/issues/6841#issuecomment-1448601349
