### ISSUE TITLE
Release 1.5.0 Checklist

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#7322]
This is a tentative list of features, no commitment on the list.

```[tasklist]
## Major Tasks
- [ ] #7141
- [ ] #7223
- [ ] https://github.com/siderolabs/talos/issues/7374
- [ ] dymanic boot asset generator (registry)
```

```[tasklist]
## Smaller Tasks
- [ ] #7191
- [ ] #7249 (Azure image upload)
- [ ] https://github.com/siderolabs/talos/issues/6391
```

```[tasklist]
## Continuous Integration
- [ ] NVIDIA e2e test
```
```[tasklist]
### Documentation Items
- [x] What's New for 1.5
- [x] Generating images (new imager)
- [x] Installing/using system extensions
- [x] Generating SecureBoot assets
- [x] KubePrism
- [ ] NVIDIA extension
```

**Comment by buroa** [comment]
🚀
