### ISSUE TITLE
optimize Talos core components memory usage

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#7532]
From a worker node:

![image](https://github.com/siderolabs/talos/assets/55211/6bf5b1d0-9147-4c06-96e2-e6170ef8a184)

`apid` is 80MiB, `dashboard` is 94MiB and `init` is 128 MiB
```[tasklist]
### COSI Improvements
- [ ] https://github.com/cosi-project/runtime/issues/305
- [ ] https://github.com/cosi-project/runtime/issues/306
- [ ] https://github.com/cosi-project/runtime/issues/307
```

```[tasklist]
### 3rd party libraries
- [ ] https://github.com/gopacket/gopacket/pull/24
- [ ] https://github.com/gopacket/gopacket/pull/32
```

```[tasklist]
### Talos Improvements
- [ ] https://github.com/siderolabs/talos/issues/7576
- [ ] https://github.com/siderolabs/talos/issues/7577
- [ ] https://github.com/siderolabs/talos/issues/7578
- [ ] https://github.com/siderolabs/talos/issues/7880
```

**Comment by smira** [comment]
There was some work done recently to optimize memory usage, but there's still some room for improvement here

**Comment by smira** [comment]
One pending potential change: https://github.com/gopacket/gopacket/pull/24

**Comment by smira** [comment]
Things got better with merged in fixes, but still a lot of room for improvement:

![image](https://github.com/siderolabs/talos/assets/55211/5e4c7d57-f3f5-47e5-a8d3-54cd61857f96)

**Comment by smira** [comment]
- [ ] big `text` section size (code, read-only, shared between Talos processes)
- [ ] big `gopclntab` section size (used for stacktraces, read-only, shared between Talos processes)
- [ ] RSS in `dashboard` doesn't show the real size of the process, as it doesn't account for `text`/`gopclntab` shared across processes
- [ ] `readelf -a -W _out/machined` provides an overview of section sizes and mapping into memory
- [ ] `gsv` wraps `bloaty` to show size per module/package (code & data)
- [ ] Go heap/stack size

**Comment by smira** [comment]
dropping `gopacket` library from `machined` reduces observed RSS down ~20 MiB
