### ISSUE TITLE
Release 1.6.0 checklist

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#7561]
This is a tentative list of features, no commitment on the list.

```[tasklist]
## Major Tasks
- [ ] https://github.com/siderolabs/talos/issues/7740
- [ ] https://github.com/siderolabs/talos/issues/4421
```

```[tasklist]
## Smaller Tasks
- [x] stop validating machine disk if installed
- [ ] https://github.com/siderolabs/talos/issues/7696
- [x] update containerd to 1.7.x
- [ ] https://github.com/siderolabs/talos/issues/7787
- [ ] https://github.com/siderolabs/talos/issues/7919
- [ ] https://github.com/siderolabs/talos/issues/7939
- [ ] https://github.com/siderolabs/talos/issues/7083
- [ ] #7911
- [ ] https://github.com/siderolabs/talos/issues/7972
- [ ] https://github.com/siderolabs/talos/issues/7507
- [ ] https://github.com/siderolabs/talos/issues/7581
- [ ] #7613
- [ ] https://github.com/siderolabs/talos/issues/7973
- [ ] https://github.com/siderolabs/talos/issues/7754
- [ ] https://github.com/siderolabs/talos/issues/7947
- [ ] https://github.com/siderolabs/talos/issues/8009
- [ ] https://github.com/siderolabs/talos/issues/7808
- [ ] https://github.com/siderolabs/talos/issues/7854
- [ ] https://github.com/siderolabs/talos/issues/7993
- [ ] #8005
- [ ] https://github.com/siderolabs/talos/issues/7995
- [ ] #8023
- [x] update Go to 1.21.5
- [ ] https://github.com/siderolabs/talos/issues/8027
- [ ] https://github.com/siderolabs/talos/issues/7994
- [x] :book: trim headings > 6 in config reference docs
- [ ] https://github.com/siderolabs/talos/issues/8057
- [ ] https://github.com/siderolabs/talos/pull/8067
- [ ] https://github.com/siderolabs/cluster-api-bootstrap-provider-talos/pull/180
- [ ] https://github.com/siderolabs/cluster-api-control-plane-provider-talos/pull/187
- [ ] https://github.com/siderolabs/sidero/pull/1258
- [ ] https://github.com/siderolabs/terraform-provider-talos/pull/138
- [ ] https://github.com/siderolabs/talos/pull/8071
- [x] submit conformance results for v1.29.0
- [ ] https://github.com/siderolabs/talos/pull/8061
```

```[tasklist]
## Continuous Integration
- [x] E2E Tests using Terraform instead of CAPI
- [x] NVIDIA e2e test
```
```[tasklist]
### Document Updates
- [x] Document updates for Trustedboot/TPM workflow, imager customization, NVIDIA drivers etc
```
