### ISSUE TITLE
Release 1.7.0 Checklist

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#8010]
This is a tentative list of features, no commitment on the list.

```[tasklist]
## Major Tasks
- [ ] https://github.com/siderolabs/talos/issues/8064
- [ ] https://github.com/siderolabs/talos/issues/8063
- [ ] https://github.com/siderolabs/talos/issues/8065
```

```[tasklist]
## Smaller Tasks
- [ ] https://github.com/siderolabs/talos/issues/8143
- [ ] https://github.com/siderolabs/talos/pull/8207
- [ ] https://github.com/siderolabs/talos/issues/7693
- [ ] https://github.com/siderolabs/extensions/issues/288
- [ ] https://github.com/siderolabs/talos/issues/8111
- [ ] https://github.com/siderolabs/talos/issues/8205
- [ ] #8202
- [ ] https://github.com/siderolabs/talos/issues/8069
- [ ] https://github.com/siderolabs/talos/issues/8197
- [ ] https://github.com/siderolabs/talos/issues/8196
- [ ] https://github.com/siderolabs/talos/issues/8328
- [ ] https://github.com/siderolabs/talos/issues/8396
- [ ] https://github.com/siderolabs/talos/issues/8329
- [ ] https://github.com/siderolabs/talos/issues/8141
- [ ] https://github.com/siderolabs/talos/issues/7356
- [ ] https://github.com/siderolabs/talos/issues/8361
- [ ] https://github.com/siderolabs/talos/issues/8440
```

```[tasklist]
## Continuous Integration
- [x] Azure e2e test
```
```[tasklist]
### Document Updates
```

**Comment by smira** [comment]
Previous: https://github.com/siderolabs/talos/issues/7561
