### ISSUE TITLE
Talos Imager Overlay implementation

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#8349]
Tasks

```[tasklist]
### Tasks
- [ ] https://github.com/siderolabs/talos/issues/8350
- [ ] https://github.com/siderolabs/talos/issues/8351
- [ ] https://github.com/siderolabs/talos/issues/8352
```
