### ISSUE TITLE
📦 Talos v1.7.0-beta.0

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#8481]
Release date: 1-2 Apr 2024

```[tasklist]
### Week of 25-29th March
- [x] Update toolchain/tools/pkgs/extras/extensions
- [x] Cut a final release of each/create a release-X.Y branch
- [x] Update tools/pkgs/extras in Talos to the final version
- [x] Update dependencies in Talos
- [x] update Go to 1.22.2, Linux kernel
```

> [!NOTE]
> There's a musl 1.2.5 which causes issues with `kmod`. `toolchain` has musl updated, but `tools` uses a previous version of the `toolchain`; we should either update all or revert toolchain.
```[tasklist]
### Tasks to complete before April 1st
- [ ] https://github.com/siderolabs/talos/issues/8514
- [ ] #7356
- [ ] #8329
- [ ] https://github.com/siderolabs/talos/issues/8141
- [ ] #8392
- [ ] https://github.com/siderolabs/talos/issues/8284
- [ ] #8361
- [ ] https://github.com/siderolabs/talos/issues/8501
- [ ] https://github.com/siderolabs/talos/issues/8498
- [ ] https://github.com/siderolabs/talos/issues/8531
- [ ] https://github.com/siderolabs/talos/pull/8502
```

```[tasklist]
### Actual release (Apr 4-5)
- [x] cut a release-1.7 branch of Talos
- [x] cut a release-1.7 branch of extensions
- [x] cut a release-1.7 branch of overlays
- [x] cut a 1.7.0-beta.0 release
- [x] update Image Factory to 1.7.0-beta.0, cut a release
- [x] Deploy new Image Factory (overlays support)
```
