### ISSUE TITLE
Talos 1.8 Release Checklist

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#8484]
This is a tentative list of features, no commitment on the list.

```[tasklist]
## Major Tasks
- [ ] https://github.com/siderolabs/talos/issues/8367
- [ ] https://github.com/siderolabs/talos/issues/8364
- [ ] https://github.com/siderolabs/talos/issues/8016
- [ ] SELinux Protection
- [ ] pre-cached images
- [ ] #7120
- [ ] https://github.com/siderolabs/talos/issues/8062
- [ ] Multiple Machine Configurations (history of Machine Configs, automatic rollback)
- [ ] https://github.com/siderolabs/talos/issues/6060
```

```[tasklist]
## Smaller Tasks
- [ ] https://github.com/siderolabs/talos/issues/8443
- [ ] https://github.com/siderolabs/talos/issues/8286
- [ ] https://github.com/siderolabs/talos/issues/7364
- [ ] https://github.com/siderolabs/talos/issues/6735
- [ ] https://github.com/siderolabs/talos/issues/8242
- [ ] #7223
- [ ] .cluster.etcd changes to restart etcd in a safe way
- [ ] https://github.com/siderolabs/talos/issues/6987
- [ ] #7088
- [ ] #7184
- [ ] https://github.com/siderolabs/talos/issues/7081
- [ ] https://github.com/siderolabs/talos/issues/6199
- [ ] https://github.com/siderolabs/talos/issues/4109
- [ ] #7141
- [ ] https://github.com/siderolabs/talos/issues/7752
- [ ] https://github.com/siderolabs/talos/issues/7688
- [ ] https://github.com/siderolabs/talos/issues/7806
- [ ] https://github.com/siderolabs/talos/issues/8035
- [ ] https://github.com/siderolabs/talos/issues/8074
```

```[tasklist]
## Continuous Integration
- [ ] Azure e2e test
- [ ] e2e aws with k8s conformance (CSI,External IP
- [ ] Migrate to GHA
```
```[tasklist]
### Document Updates
```
