### ISSUE TITLE
list of open issues on converting CI to GHA

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#8781]
```[tasklist]
### Tasks
- [x] use 'large' runners
- [x] rework 'crashdump' feature to use artifacts to capture all relevant logs
- [x] split 'integration-misc' into some smaller groups (it runs for too long now)
- [x] reprovision EM nodes with correct platform
- [x] print node name (system info) on the job start
- [ ] buildkit cache management - size being used (?) / prune the cache
```

**Comment by frezbo** [comment]
Large runners is fixed by https://github.com/siderolabs/talos/pull/8778

**Comment by frezbo** [comment]
Printing node name is handled in #8783

**Comment by sanmai-NL** [comment]
Services like [Depot](https://depot.dev/) solve a lot of the complexity and performance challenges around Buildkit cache management. You can contact them for an OSS plan.

**Comment by frezbo** [comment]
crashdump is fixed in #8812
