### ISSUE TITLE
Refactoring initialize sequence tasks

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#8897]
Goal: reduce number of tasks in the `initialize` sequence, eventually get rid of the sequence.

```[tasklist]
### Tasks
- [ ] https://github.com/siderolabs/talos/issues/8898
- [ ] https://github.com/siderolabs/talos/issues/8899
- [ ] https://github.com/siderolabs/talos/issues/8900
```
