### ISSUE TITLE
📦 Talos v1.8.0-alpha.1

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#8965]
```[tasklist]
### Tasks
- [ ] https://github.com/siderolabs/talos/pull/8964
- [ ] https://github.com/siderolabs/extensions/pull/423
- [ ] https://github.com/siderolabs/talos/pull/8962
- [x] release/cut overlays
```
