### ISSUE TITLE
Talos 1.9 Release Checklist :white_check_mark:  

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#9249]
Previous: #8484 

This is a tentative list of features, no commitment on the list.

```[tasklist]
## Major Tasks
- [ ] https://github.com/siderolabs/talos/issues/8367
- [ ] https://github.com/siderolabs/talos/issues/9610
- [ ] https://github.com/siderolabs/talos/issues/8016
- [ ] SELinux Protection
- [ ] https://github.com/siderolabs/talos/issues/8364
- [ ] #7120
- [ ] https://github.com/siderolabs/talos/issues/8062
- [ ] Multiple Machine Configurations (history of Machine Configs, automatic rollback)
```

```[tasklist]
## Smaller Tasks
- [ ] https://github.com/siderolabs/talos/issues/9729
- [ ] https://github.com/siderolabs/talos/issues/8074
- [ ] https://github.com/siderolabs/talos/issues/9342
- [ ] https://github.com/siderolabs/talos/issues/9753#issuecomment-2485907212
- [ ] https://github.com/siderolabs/talos/issues/7081
- [ ] https://github.com/siderolabs/talos/issues/8720
- [ ] https://github.com/siderolabs/talos/issues/9336
- [ ] https://github.com/siderolabs/talos/issues/9543
- [ ] https://github.com/siderolabs/talos/issues/9552
- [ ] https://github.com/siderolabs/talos/issues/9565
- [ ] https://github.com/siderolabs/talos/issues/9607
- [ ] https://github.com/siderolabs/talos/issues/9728
- [ ] https://github.com/siderolabs/talos/issues/9691
- [ ] https://github.com/siderolabs/talos/issues/9827
```

```[tasklist]
## Continuous Integration
```

```[tasklist]
### Document Updates
```
