### ISSUE TITLE
pre-cached images

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#9610]
```[tasklist]
### Tasks
- [ ] https://github.com/siderolabs/talos/issues/9611
- [ ] https://github.com/siderolabs/talos/issues/9612
- [ ] https://github.com/siderolabs/talos/issues/9613
- [ ] https://github.com/siderolabs/talos/issues/9614
- [ ] https://github.com/siderolabs/talos/issues/9746
- [ ] https://github.com/siderolabs/talos/issues/9616
- [ ] https://github.com/siderolabs/talos/issues/9615
- [ ] https://github.com/siderolabs/talos/issues/9860
```

**Comment by DmitriyMV** [comment]
Closed with #9860 merged.
