### ISSUE TITLE
configuring image cache

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#9614]
For security reasons, image cache is enabled only if the machine config has `machine.features.imageCache`.

It is only enabled if the image cache volume was found.

The local registry service #9612 should be fed with the path(s) of the discovered images cache volumes.

Registry mirror configuration should be adjusted on the fly to include local registry service endpoint as the first entry.
```[tasklist]
### Tasks
- [ ] https://github.com/siderolabs/talos/issues/9766
- [ ] https://github.com/siderolabs/talos/issues/9767
```

**Comment by smira** [comment]
We need a controller which takes machine config as an input, and outputs a resource which implements `config.Registries` interfaces. 

In `image/pull.go`, read this resource instead of machine config.

In `cri_registry_config.go`, read this resource instead of machine config.

If image cache is enabled (and we found a volume), this resource is updated to include the registryd endpoint as the first endpoint for all configured mirrors, and for `*` (even if it's not configured yet).

**Comment by smira** [comment]
```tasklist
- [ ] split out config.Registries to a resource and re-wire the controllers
- [ ] volume config, mounting, registry config
````
