### ISSUE TITLE
unify boot assets in the intaller/image to be UKIs

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#9633]
## Feature Request

Instead of having separate images for UKIs and raw boot assets, settle down on having UKIs always.

We can have some format to extract necessary bits from the UKI, e.g. `talos.uki:<section_name>`. Support in the `imager`/`installer` to extract a raw bit from the UKI for non-sd-boot systems.

Support generating unsigned UKIs.

In Image Factory, drop the distinction between `installer` and `installer-secureboot` by always enabling SecureBoot for the installer.

### Description

```[tasklist]
### Tasks
- [ ] https://github.com/siderolabs/talos/issues/9688
- [ ] https://github.com/siderolabs/talos/issues/10101
- [x] go-ukify multi profile support
- [ ] https://github.com/siderolabs/talos/issues/10075
- [ ] https://github.com/siderolabs/talos/issues/10323
- [ ] https://github.com/siderolabs/talos/issues/10332
- [ ] https://github.com/siderolabs/talos/issues/10339
- [ ] https://github.com/siderolabs/talos/issues/10349
```
