### ISSUE TITLE
Talos 1.9: bump toolchain/tools/pkgs/extensions, cut releases

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#9821]
```[tasklist]
### Tasks
- [x] toolchain
- [x] tools: bumps
- [x] tools: release
- [x] pkgs: linux 6.12
- [x] pkgs: other bumps
- [x] pkgs: release
- [x] extensions: linux 6.12
- [x] extensions: libnvidia-container
- [x] extensions: bump
- [x] extras: bump
- [x] extras: release
- [x] Talos: bump deps
```
