### ISSUE TITLE
Talos 1.10 Release Checklist

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#9899]
Previous: #9249 
Previous: #8484 

This is a tentative list of features, no commitment on the list.

```[tasklist]
## Major Tasks
- [ ] https://github.com/siderolabs/talos/issues/8367
- [ ] https://github.com/siderolabs/talos/issues/9610
- [ ] https://github.com/siderolabs/talos/issues/8016
- [ ] SELinux Protection
- [ ] https://github.com/siderolabs/talos/issues/8364
- [ ] #7120
- [ ] https://github.com/siderolabs/talos/issues/8062
- [ ] Multiple Machine Configurations (history of Machine Configs, automatic rollback)
```

```[tasklist]
## Smaller Tasks
- [ ] #7223
- [ ] resources for network and disk usage (for Omni dashboard)
- [ ] https://github.com/siderolabs/talos/issues/4174
- [ ] https://github.com/siderolabs/talos/issues/6199
- [ ] https://github.com/siderolabs/talos/issues/8746#issuecomment-2113676667
- [ ] https://github.com/siderolabs/talos/issues/8286
- [ ] https://github.com/siderolabs/talos/issues/7364
- [ ] https://github.com/siderolabs/talos/issues/8779
- [ ] https://github.com/siderolabs/talos/issues/9173
- [ ] https://github.com/siderolabs/talos/issues/8972
- [ ] https://github.com/siderolabs/talos/issues/8242
- [ ] .cluster.etcd changes to restart etcd in a safe way
- [ ] https://github.com/siderolabs/talos/issues/6987
- [ ] #7088
- [ ] https://github.com/siderolabs/talos/issues/9545
- [ ] https://github.com/siderolabs/talos/issues/9609
- [ ] #7184
- [ ] https://github.com/siderolabs/talos/issues/4109
- [ ] #7141
- [ ] https://github.com/siderolabs/talos/issues/9729
- [ ] https://github.com/siderolabs/talos/issues/7752
- [ ] https://github.com/siderolabs/talos/issues/7688
- [ ] https://github.com/siderolabs/talos/issues/7806
- [ ] https://github.com/siderolabs/talos/issues/8074
- [ ] https://github.com/siderolabs/talos/issues/8702
- [ ] https://github.com/siderolabs/talos/issues/8597
- [ ] https://github.com/siderolabs/talos/issues/9347
- [ ] https://github.com/siderolabs/talos/issues/9342
- [ ] https://github.com/siderolabs/talos/issues/9372
- [ ] https://github.com/siderolabs/image-factory/issues/154
- [ ] https://github.com/siderolabs/talos/issues/9753#issuecomment-2485907212
- [ ] https://github.com/siderolabs/talos/issues/7081
- [ ] https://github.com/siderolabs/talos/issues/8720
- [ ] https://github.com/siderolabs/talos/issues/9336
- [ ] https://github.com/siderolabs/talos/issues/9543
- [ ] https://github.com/siderolabs/talos/issues/9552
- [ ] https://github.com/siderolabs/talos/issues/9565
- [ ] https://github.com/siderolabs/talos/issues/9607
- [ ] https://github.com/siderolabs/talos/issues/9728
- [ ] https://github.com/siderolabs/talos/issues/9691
- [ ] https://github.com/siderolabs/talos/issues/9814
- [ ] https://github.com/siderolabs/talos/issues/9827
```

```[tasklist]
## Continuous Integration
- [ ] e2e aws with k8s conformance (CSI,External IP
- [ ] https://github.com/siderolabs/talos/issues/9669
```

```[tasklist]
### Document Updates
```
